

export const SUB_MENU = [
  {
    menuId: 'TRANSACTION',
    pMenuId: '',
    menuNm: 'Transaction',
    trnslNm: 'Transaction',
    menuDp: 2,
    menuUrl: 'Transaction',
    menuTypeCd: 'C',
    sortOrd: 2,
    menuIcon: null,
    dsplyYn: 'Y',
    useYn: 'Y',
  },
  {
    menuId: 'TRANSACTION_LIST',
    pMenuId: 'TRANSACTION',
    menuNm: 'Transaction List',
    trnslNm: 'Transaction List',
    menuDp: 3,
    menuUrl: 'transaction/transactionList',
    menuTypeCd: 'P',
    sortOrd: 0,
    menuIcon: null,
    dsplyYn: 'Y',
    useYn: 'Y',
  },
  {
    menuId: 'ADMIN',
    pMenuId: '',
    menuNm: 'ADMIN',
    trnslNm: 'ADMIN',
    menuDp: 2,
    menuUrl: 'admin',
    menuTypeCd: 'C',
    sortOrd: 1,
    menuIcon: null,
    dsplyYn: 'Y',
    useYn: 'Y',
  },
  {
    menuId: 'USER',
    pMenuId: 'ADMIN',
    menuNm: 'User Manager',
    trnslNm: 'User Manager',
    menuDp: 2,
    menuUrl: 'admin/userManager',
    menuTypeCd: 'P',
    sortOrd: 1,
    menuIcon: null,
    dsplyYn: 'Y',
    useYn: 'Y',
  },
  {
    menuId: 'APPROVE',
    pMenuId: 'ADMIN',
    menuNm: 'approve',
    trnslNm: 'approve',
    menuDp: 2,
    menuUrl: 'admin/approve',
    menuTypeCd: 'P',
    sortOrd: 2,
    menuIcon: null,
    dsplyYn: 'Y',
    useYn: 'Y',
  },
];
